# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := cortex-a53

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53

# Boot
LZMA_RAMDISK_TARGETS := true
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --board SRPQH16A001RU --dt device/samsung/crownlte/prebuilt/dtb.img
# BOARD_KERNEL_SEPARATED_DT := true
# BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --board SRPQH16A001RU
# TARGET_CUSTOM_DTBTOOL := dtbhtoolExynos
# BOARD_CUSTOM_BOOTIMG_MK := device/samsung/crownlte/mkbootimg.mk

# File systems
BOARD_SEPOLICY_VERS := 28.0
PRODUCT_FULL_TREBLE := true
LZMA_RAMDISK_TARGETS := recovery
BOARD_HAS_LARGE_FILESYSTEM := true
RECOVERY_SDCARD_ON_DATA := true
TARGET_RECOVERY_FSTAB := device/samsung/crownlte/recovery.fstab
TARGET_RECOVERY_DEVICE_DIRS := device/samsung/crownlte
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TW_INCLUDE_FUSE_EXFAT := true
TW_INCLUDE_FUSE_NTFS := true
TW_INCLUDE_NTFS_3G := true
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4 f2fs


# Graphical
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_RECOVERY_PIXEL_FORMAT := ABGR_8888
TW_BRIGHTNESS_PATH := /sys/class/backlight/panel/brightness
TW_DEFAULT_BRIGHTNESS := 10200
TW_MAX_BRIGHTNESS := 25500
TW_THEME := portrait_hdpi

# Kernel
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CONFIG := crownlte_twrp_defconfig
TARGET_KERNEL_SOURCE := kernel/samsung/crownlte-gsi-endurance

# Platform
BOARD_NEEDS_VENDORIMAGE_SYMLINK := false
BOARD_VENDOR := samsung
TARGET_BOARD_PLATFORM := exynos5
TARGET_BOOTLOADER_BOARD_NAME := universal9810
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
TARGET_SOC := exynos9810

# Recovery
RECOVERY_VARIANT := twrp
TW_EXCLUDE_SUPERSU := true
TW_EXTRA_LANGUAGES := true
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := true
# TW_INPUT_BLACKLIST := "sec_e-pen-pad"
TW_NO_REBOOT_BOOTLOADER := true
TW_USE_NEW_MINADBD := true
TW_EXCLUDE_TWRPAPP := true
TW_USE_TOOLBOX := true

# Include
# TARGET_SPECIFIC_HEADER_PATH := device/samsung/crownlte/include
