#!/sbin/sh
busybox mount `echo $@ | sed '/system_root/! s/system/system_root/'`
if echo $@ | grep -Fq /system ; then
  rm -rf /system >/dev/null 2>&1
  rm -rf /system/system >/dev/null 2>&1
  rmdir -p /system >/dev/null 2>&1
  ln -s /system_root/system /system
  ln -s /system_root/system /system/system
fi
