#!/sbin/sh
busybox mount `echo $@ | sed '/system_root/! s/system/system_root/'`;
if echo $@ | grep -q system ; then
  rm -f /system >/dev/null 2>&1
  rmdir /system >/dev/null 2>&1
  ln -s /system_root/system /system
fi;
